version: '3.8'

services:
  ollama_server:
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    expose:
      - 11434/tcp
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest  # Official Ollama image
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  

  flask_server:
    container_name: flask
    build:
      context: .
      dockerfile: ./dockerfile  # Path to the Dockerfile for Flask web server
    image: poc/flask_server
    ports:
      - "5000:5000"
    expose:
      - 5000/tcp
    environment:
      - "OLLAMA_API_BASE_URL=http://localhost:11434/api"
    depends_on:
      - ollama_server
    network_mode: host


volumes:
  ollama:
    name: ollama_models
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /media/ollama_models


# networks:
#   ollama_network:
#     driver: bridge