version: '3.8'

services:
  ollama_server:
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest  # Official Ollama image
    networks:
     - bridge_net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  

  flask_server:
    container_name: flask
    build:
      context: .
      dockerfile: ./dockerfile  # Path to the Dockerfile for Flask web server
    image: poc/flask_server
    ports:
      - "5000:5000"
    environment:
      - "OLLAMA_HOST=0.0.0.0:11434"
      - "OLLAMA_ORIGINS=http://172.23.0.2:*"
      - "OLLAMA_API_BASE_URL=http://ollama:11434/api"
    depends_on:
      - ollama_server
    networks:
      - bridge_net
      # - host_net
  

networks:
  bridge_net:
    driver: bridge
  host_net:
    driver: host


volumes:
  ollama:
    name: ollama_models
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /media/ollama_models
